name: Generate Example

on:
  push:
    branches:
      - main
jobs:
  generate-example:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - name: Run Build
        run: cargo build --bin compiler --release

      - name: Generate example
        run: |
          docker run --rm -v $PWD:/vhs ghcr.io/charmbracelet/vhs example.tape

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "example.gif"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
